export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const ADD_USER = "ADD_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";

export const GET_VEHICULE_LIST = "GET_VEHICULE_LIST";
export const GET_VEHICULE_LIST_SUCCESS = "GET_VEHICULE_LIST_SUCCESS";
