export const GET_USER_LIST = "GET_USER_LIST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const ADD_USER = "ADD_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const EDIT_USER = "EDIT_USER";

export const GET_VEHICULE_LIST = "GET_VEHICULE_LIST";
export const GET_VEHICULE_LIST_SUCCESS = "GET_VEHICULE_LIST_SUCCESS";
export const ADD_VEHICULE = "ADD_VEHICULE";

export const ADD_MISSION = "ADD_MISSION";
export const GET_MISSION_LIST = "GET_MISSION_LIST";
export const GET_MISSION_LIST_SUCCESS = "GET_MISSION_LIST_SUCCESS";

export const ADD_FICHETECH = "ADD_FICHETECH";
export const GET_FICHETECH_LIST = "GET_FICHETECH_LIST";
export const GET_FICHETECH_LIST_SUCCESS = "GET_ALLFICHETECH_LIST_SUCCESS";
//export const GET_ALLFICHETECH_LIST_SUCCESS = "GET_ALLFICHETECH_LIST_SUCCESS";


export const GET_FICHEDEP_LIST = "GET_FICHEDEP_LIST";
export const GET_FICHEDEP_LIST_SUCCESS = "GET_FICHEDEP_LIST_SUCCESS";
export const ADD_FICHEDEP = "ADD_FICHEDEP";

export const GET_RECLAMATION_LIST ="GET_RECLAMATION_LIST";
export const GET_RECLAMATION_LIST_SUCCESS ="GET_RECLAMATION_LIST_SUCCESS";




